export const UI_TEXT = {
  gameTitle: "たいぴんぐ げーむ",
  play: "あそぶ",
  admin: "かんり",
  next: "つぎへ",
  retry: "もういちど",
  back: "もどる",
  upload: "あっぷろーど",
  delete: "さくじょ",
  save: "ほぞん",
  word: "ことば",
  displayName: "なまえ",
  image: "えをえらぶ",
  nextLetter: "つぎのもじ",
  tryAgain: "もういちど！",
  celebrations: ["すごい！", "やったね！", "できたよ！", "ばんざい！"],
  loading: "よみこみちゅう...",
  selectGame: "どれであそぶ？",
  musicOn: "おんがく おん",
  musicOff: "おんがく おふ",
  noGames: "げーむが まだ ないよ",
  addFromAdmin: "かんりから ついか してね",
  typingMode: "にゅうりょく",
  alphabet: "えいご (ABC)",
  hiragana: "ひらがな",
} as const;
